Inclusion #5: Parafac2 implementation: factorization.py and plots of parafac2 results
meyer-lab/mrsa-ca pull request #12
Opened 2024-09-18 00:22 UTC by MrBones1102

factorization.py and plotting of parafac2 results: CA time data, data reconstructions (stopped at 3 ranks for disease to build quicker for checks), and disease data (MRSA, CA, Breast Cancer, Healthy)

2024-09-18 00:25 UTC, MrBones1102 commented
Build action error was not updating until after I submitted the pull request. Now that I see where it failed, I can fix it. As for the test build which failed to get a specific dependency, I'm not sure what's happening there, as I have not changed anything about the environment since the last PR.

2024-09-18 16:38 UTC, aarmey requested changes
Just one comment before merging.

2024-09-18 16:38 UTC, aarmey commented on mrsa_ca_rna/figures/figure10.py
> +    time_data, _, _ = ca_data_split(scale=True, tpm=True)
Do you anticipate importing the data without `scale=True` or `tpm=True`? If not, I would remove these as options to the function.

2024-09-19 00:45 UTC, MrBones1102 commented on mrsa_ca_rna/figures/figure10.py
> +    time_data, _, _ = ca_data_split(scale=True, tpm=True)
For the `ca_data_split()`, likely not, unless being "double scaled" is an issue once it gets concatenated with other data and then scaled again with that data. I've wanted to revisit `import_data.py` for a while and rework some old names, parameters, and methods so I'm grateful for the feedback.

Additionally, I was thinking about the disease data handling and was wondering specifically for parafac2 analysis, when the scaling should occur. Currently, I have all the disease data import, then concatenate into a large 2D matrix, which then gets scaled. From there, it is split into slices along the disease axis as an xarray and passed to parafac2. Is there data leakage here because I am scaling all the data together before handing it to parafac2, and should I avoid it by splitting into slices first and then scaling the slices independently?

2024-09-20 01:29 UTC, aarmey commented on mrsa_ca_rna/figures/figure10.py
> +    time_data, _, _ = ca_data_split(scale=True, tpm=True)
No. The way you describe it sounds correct. We can talk about why when I'm back.

2024-09-23 20:42 UTC, aarmey approved these changes
Merging!

2024-09-23 20:42 UTC, merged