Pf2 component regression
meyer-lab/mrsa-ca pull request #22
Opened 2024-10-02 23:33 UTC by MrBones1102

2024-10-02 23:45 UTC, MrBones1102 commented
This relies on branch: PCA and PLSR component analysis and ROC curves of classifications. #16. Solve those errors first

2024-10-03 04:03 UTC, MrBones1102 commented
I did not expect to get a very accurate prediction model with so few training points, but the confusion matrix that resulted was more interesting than I expected

2024-10-03 15:29 UTC, aarmey requested changes

2024-10-03 15:29 UTC, aarmey commented on mrsa_ca_rna/figures/figure12a.py
> +    tensor_decomp, _ = perform_parafac2(disease_xr, rank=rank)
If you are using Pf2 as the factorization, how do you build a classification model? Doesn't the first factor matrix just have one row per disease?

2024-10-14 17:16 UTC, closed without merging