6 24 feedback
meyer-lab/mrsa-ca pull request #3
Opened 2024-07-01 21:36 UTC by MrBones1102

Adding feedback from last week's meeting as well as further developing the basic structure of the repository.

2024-07-02 13:33 UTC, aarmey commented
Does this include everything from PR #2?

2024-07-02 13:45 UTC, aarmey requested changes
Some initial stuff. You can also run ruff to format things. `poetry add ruff` and then `poetry run ruff format .`

2024-07-02 20:22 UTC, MrBones1102 commented on mrsa_ca_rna/figures/figure02_pca_loadings.py
> +    loadings = pd.DataFrame(pca.components_, index=rows, columns=rna_mat.columns)
Moved this to perform_PCA and changed the function to output scores (dataFrame), loadings (dataFrame), and pca (object).

I want to incorporate more of the metadata into perform_PCA to make the outputs more useful for plotting, like you suggested. Everything required to plot anything relevant to these data could be made easily accessible if they are included in the dataframes themselves instead of needing to fetch it all the time.

2024-07-05 15:39 UTC, aarmey approved these changes
This looks good to merge. I'm just going to ruff format before I do so.

2024-07-05 15:40 UTC, merged