figure03b plots of randomized data in comparison to true data
meyer-lab/mrsa-ca pull request #32
Opened 2024-11-21 22:06 UTC by MrBones1102

Added MRSA regression analysis using randomized PCA component data or shuffled statuses to see if patterns determining outcome in original data is significantly different from random.

2024-11-22 19:51 UTC, aarmey requested changes
One change, then this looks great.

2024-11-30 01:37 UTC, MrBones1102 commented
Added random orthogonal matrix. It requires a bit more computation time since it needs to generate such a large NxN matrix which I can then subset from.

2024-12-02 15:00 UTC, aarmey requested changes
More changes.

2024-12-02 15:00 UTC, aarmey commented on mrsa_ca_rna/figures/figure03b.py
> +    random_pca = random_SVD[:, :70]
Didn't realize this only created square matrices. You can then just create a random matrix of the correct size and then use QR decomposition to orthogonalize.

2024-12-02 15:00 UTC, aarmey commented on mrsa_ca_rna/figures/figure03b.py
> +    for i, key in enumerate(proba_dict):
Just make a function that makes the plot for one entry of proba_dict. This would get rid of a loop inside the function above.

2024-12-02 15:00 UTC, aarmey commented on mrsa_ca_rna/figures/figure03b.py
> +    """Perform similar analysis of figure03a, but with random pca"""
Don't reference another figure in the description. Just describe what this is doing plainly.

2024-12-02 15:00 UTC, aarmey commented on mrsa_ca_rna/figures/figure03b.py
> +            _, model = perform_PC_LR(data_value, status_value, return_clf=True)
Hasn't this function already done cross-validation?

2024-12-02 15:00 UTC, aarmey commented on mrsa_ca_rna/figures/figure03b.py
> +    for i, key in enumerate(proba_dict):
I don't like looping to accumulate results, then looping to plot all the results. It's unnecessarily convoluted.

2024-12-02 15:00 UTC, aarmey commented on mrsa_ca_rna/figures/figure03b.py
> +# main module imports
Make docstring for overall file.

2024-12-02 15:00 UTC, aarmey commented on mrsa_ca_rna/figures/figure03b.py
> +# main module imports
I also think it would be good to organize your figure files a bit more. I tried to find your Pf2 analysis and had lots of trouble navigating your code. Perhaps all of this sort of analysis could have "_project_" in the name? Then the Pf2 analysis could have "_pf2_"?

2025-02-22 14:40 UTC, aarmey requested changes

2025-02-22 14:40 UTC, aarmey commented on mrsa_ca_rna/figures/figure_pca_random_comparison.py
> +    _, _, ca_pca = perform_pca(ca_data.to_df())
Why doesn't this take a number of components?

2025-02-22 14:40 UTC, aarmey commented on mrsa_ca_rna/figures/figure_pca_random_comparison.py
> +    random_matrix = np.random.rand(X.shape[1], ca_pca.components_.shape[0])
Look here: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ortho_group.html#scipy.stats.ortho_group

I like that this function is a little more explicit about what you are doing.

2025-02-22 14:40 UTC, aarmey commented on mrsa_ca_rna/figures/figure_pca_random_comparison.py
> +    true_mrsa, true_score = make_roc_curve(mrsa_dict["mrsa"], y_true, y_true)
Why does this function take `y_true` twice?

2025-02-24 17:54 UTC, MrBones1102 commented on mrsa_ca_rna/figures/figure_pca_random_comparison.py
> +    random_matrix = np.random.rand(X.shape[1], ca_pca.components_.shape[0])
We had previously used that function but it can only generate an NxN orthogonal matrix. There was excess computation time spent generating a `(X.shape[0], X.shape[0])` matrix only to then cut it down to `(X.shape[0], desired_comp)` to keep the size similar to a pca decomposition of X.

But I agree regarding the clarity of using the explicit function and I'll swap back to it.

2025-02-25 03:08 UTC, aarmey approved these changes

2025-02-25 16:44 UTC, merged