Pf2 implementation
meyer-lab/mrsa-ca pull request #6
Opened 2024-08-25 07:48 UTC by MrBones1102

Adding parafac2 analysis of time data in the CA dataset, and of patients across diseases

2024-08-26 03:46 UTC, aarmey requested changes
Looks good! One suggestion here. Also, please resolve the merge conflict. Have you taken a look at why the build is failing?

2024-08-26 03:46 UTC, aarmey commented on mrsa_ca_rna/import_data.py
> +def extract_time_data(scaled: tuple = (True, 0)):
This is an unusual way to pass in this information. I would recommend splitting this into two arguments, `scale` boolean and `scale_value`.

2024-08-27 20:05 UTC, aarmey commented on mrsa_ca_rna/factorization.py
> +        data_list, rank=rank, n_iter_max=2000, verbose=True, return_errors=True
@MrBones1102 use `init="svd"`, `svd="randomized_svd"`, and `normalize_factors=True`. This should provide a faster and more consistent result.

2024-08-27 20:16 UTC, MrBones1102 commented
> Looks good! One suggestion here. Also, please resolve the merge conflict. Have you taken a look at why the build is failing?

Yes, I just went through yesterday and some of my early figure files need refactoring to work with the AnnData methods I'm using instead of the multiindex pandas.

I plan to have everything fixed up by the end of the day today.

2024-08-30 18:39 UTC, merged