Inclusion #2: Plotting of Logistic Regression of PCA'd data w/ MRSA and CA datasets
meyer-lab/mrsa-ca pull request #8
Opened 2024-09-12 21:23 UTC by MrBones1102

This is the second split of the Regression PR. It includes plotting for logistic regression of the MRSA and CA datasets.

2024-09-13 13:35 UTC, aarmey requested changes

2024-09-13 13:35 UTC, aarmey commented on mrsa_ca_rna/figures/figure03_RegressionScore.py
> +    performance_dict = datasets.copy()
Why do you need a copy of this? Can't you just add information to `datasets`?

2024-09-13 13:35 UTC, aarmey commented on mrsa_ca_rna/figures/figure03_RegressionScore.py
> +    comp_arr = np.arange(1, components + 1)
Just make this where you need it.

2024-09-13 13:35 UTC, aarmey commented on mrsa_ca_rna/figures/figure03_RegressionScore.py
> +        performance_df = pd.DataFrame(
Rather than concatenate, then create a dataframe, you can create a dataframe from a dictionary. Something like `pd.Dataframe({"Comp": np.arange, "Performance": performance})`. This is much more readable.

2024-09-13 13:35 UTC, aarmey commented on mrsa_ca_rna/figures/figure03_RegressionScore.py
> +            y_data = whole_data.obs.loc[whole_data.obs["disease"] == "MRSA", "status"]
Because y_data is always the same, I'd move it out of the loop.

2024-09-13 13:35 UTC, aarmey commented on mrsa_ca_rna/figures/figure04.py
> +        weighted_rna.iloc[pat, :] = weighted_rna.iloc[pat, :].values * weights
I think you're going to have a much easier time inspecting the weights of the model, than weighting the underlying data and looking for patterns...

2024-09-13 13:35 UTC, aarmey commented on mrsa_ca_rna/figures/figure04.py
> +    for col in weighted_rna.columns:
This looks like something that can be vectorized. Can't you do a `np.sum(X, axis=0`?

2024-09-13 13:35 UTC, aarmey commented on mrsa_ca_rna/figures/figure04.py
> +    total_df = pd.DataFrame(
Yeah... I think you're trying to extract information from the dataset that should be evident in the model parameters themselves.

2024-09-13 20:22 UTC, MrBones1102 commented
@aarmey I incorporated your suggested changes to figure03, it makes a lot more sense now. I removed figure04 entirely because I feel like it just wasn't showing something useful. Incidentally, I had started a new branch for making figures related to dissecting the components more directly using the weights, which I feel like was figure04's intended purpose, so I would likely have replaced figure04 with these new figures anyway.
Plus, figure04 was very heavy computationally.

Side note: I apologize if this method of interaction is improper. Please let me know if you have a more preferred method or format for receiving rationale or communication.

2024-09-14 01:18 UTC, aarmey commented
@MrBones1102 communication on here is always great, so long as you keep your pull requests reasonably organized! It's much easier to discuss code changes because comments and changes can be organized next to each other.

2024-09-14 01:19 UTC, aarmey approved these changes
Ready to merge.

2024-09-14 18:43 UTC, merged